**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/grouping-and-sorting).**

---

# Introduction

In these exercises we'll apply groupwise analysis to our dataset.

Run the code cell below to load the data before running the exercises.

In [30]:
import pandas as pd

reviews = pd.read_csv("../input/wine-reviews/winemag-data-130k-v2.csv", index_col=0)
#pd.set_option("display.max_rows", 5)

from learntools.core import binder; binder.bind(globals())
from learntools.pandas.grouping_and_sorting import *
print("Setup complete.")

Setup complete.

In [2]:
reviews.groupby("points").points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [4]:
reviews.groupby("country").country.count()

country
Argentina                  3800
Armenia                       2
Australia                  2329
Austria                    3345
Bosnia and Herzegovina        2
Brazil                       52
Bulgaria                    141
Canada                      257
Chile                      4472
China                         1
Croatia                      73
Cyprus                       11
Czech Republic               12
Egypt                         1
England                      74
France                    22093
Georgia                      86
Germany                    2165
Greece                      466
Hungary                     146
India                         9
Israel                      505
Italy                     19540
Lebanon                      35
Luxembourg                    6
Macedonia                    12
Mexico                       70
Moldova                      59
Morocco                      28
New Zealand                1419
Peru                         16
Portugal                   5691
Romania                     120
Serbia                       12
Slovakia                      1
Slovenia                     87
South Africa               1401
Spain                      6645
Switzerland                   7
Turkey                       90
US                        54504
Ukraine                      14
Uruguay                     109
Name: country, dtype: int64

In [44]:
reviews.groupby("country").price.max()

country
Argentina                  230.0
Armenia                     15.0
Australia                  850.0
Austria                   1100.0
Bosnia and Herzegovina      13.0
Brazil                      60.0
Bulgaria                   100.0
Canada                     120.0
Chile                      400.0
China                       18.0
Croatia                     65.0
Cyprus                      21.0
Czech Republic              45.0
Egypt                        NaN
England                     95.0
France                    3300.0
Georgia                     40.0
Germany                    775.0
Greece                      79.0
Hungary                    764.0
India                       20.0
Israel                     150.0
Italy                      900.0
Lebanon                     75.0
Luxembourg                  30.0
Macedonia                   20.0
Mexico                     108.0
Moldova                     42.0
Morocco                     40.0
New Zealand                130.0
Peru                        68.0
Portugal                  1000.0
Romania                    320.0
Serbia                      42.0
Slovakia                    16.0
Slovenia                    90.0
South Africa               330.0
Spain                      770.0
Switzerland                160.0
Turkey                     120.0
US                        2013.0
Ukraine                     13.0
Uruguay                    130.0
Name: price, dtype: float64

In [10]:
reviews.groupby("country").points.max()

country
Argentina                  97
Armenia                    88
Australia                 100
Austria                    98
Bosnia and Herzegovina     88
Brazil                     89
Bulgaria                   91
Canada                     94
Chile                      95
China                      89
Croatia                    91
Cyprus                     89
Czech Republic             89
Egypt                      84
England                    95
France                    100
Georgia                    92
Germany                    98
Greece                     93
Hungary                    97
India                      93
Israel                     94
Italy                     100
Lebanon                    91
Luxembourg                 90
Macedonia                  89
Mexico                     92
Moldova                    91
Morocco                    93
New Zealand                95
Peru                       86
Portugal                  100
Romania                    92
Serbia                     89
Slovakia                   87
Slovenia                   92
South Africa               95
Spain                      98
Switzerland                90
Turkey                     92
US                        100
Ukraine                    88
Uruguay                    92
Name: points, dtype: int64

In [11]:
reviews.loc[(reviews.points == 100) & (reviews.country == "US")]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
45798,US,Tasted in a flight of great and famous Napa wi...,NaN,100,200.0,California,Napa Valley,Napa,NaN,NaN,Cardinale 2006 Cabernet Sauvignon (Napa Valley),Cabernet Sauvignon,Cardinale
113929,US,In 2005 Charles Smith introduced three high-en...,Royal City,100,80.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Charles Smith 2006 Royal City Syrah (Columbia ...,Syrah,Charles Smith
118058,US,This wine dazzles with perfection. Sourced fro...,La Muse,100,450.0,California,Sonoma County,Sonoma,NaN,NaN,Verité 2007 La Muse Red (Sonoma County),Bordeaux-style Red Blend,Verité
123545,US,Initially a rather subdued Frog; as if it has ...,Bionic Frog,100,80.0,Washington,Walla Walla Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Cayuse 2008 Bionic Frog Syrah (Walla Walla Val...,Syrah,Cayuse

In [15]:
reviews.groupby(["country","province"]).apply(lambda df: df.loc[df.points.idxmax()])

                              country  \
country   province
Argentina Mendoza Province  Argentina
          Other             Argentina
Armenia   Armenia             Armenia
Australia Australia Other   Australia
          New South Wales   Australia
...                               ...
Uruguay   Juanico             Uruguay
          Montevideo          Uruguay
          Progreso            Uruguay
          San Jose            Uruguay
          Uruguay             Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price          province                 region_1  \
country   province
Argentina Mendoza Province  120.0  Mendoza Province                  Mendoza
          Other              90.0             Other                    Salta
Armenia   Armenia            15.0           Armenia                      NaN
Australia Australia Other    15.0   Australia Other  South Eastern Australia
          New South Wales    32.0   New South Wales          New South Wales
...                           ...               ...                      ...
Uruguay   Juanico            45.0           Juanico                      NaN
          Montevideo         60.0        Montevideo                      NaN
          Progreso           46.0          Progreso                      NaN
          San Jose           50.0          San Jose                      NaN
          Uruguay            22.0           Uruguay                      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
Armenia   Armenia               NaN      Mike DeSimone        @worldwineguys
Australia Australia Other       NaN                NaN                   NaN
          New South Wales       NaN     Joe Czerwinski                @JoeCz
...                             ...                ...                   ...
Uruguay   Juanico               NaN  Michael Schachner           @wineschach
          Montevideo            NaN  Michael Schachner           @wineschach
          Progreso              NaN  Michael Schachner           @wineschach
          San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 13 columns]

In [18]:
sorted_by_country = reviews.groupby(["country"]).price.agg([len,min,max])
sorted_by_country

                          len   min     max
country
Argentina                3800   4.0   230.0
Armenia                     2  14.0    15.0
Australia                2329   5.0   850.0
Austria                  3345   7.0  1100.0
Bosnia and Herzegovina      2  12.0    13.0
Brazil                     52  10.0    60.0
Bulgaria                  141   8.0   100.0
Canada                    257  12.0   120.0
Chile                    4472   5.0   400.0
China                       1  18.0    18.0
Croatia                    73  12.0    65.0
Cyprus                     11  11.0    21.0
Czech Republic             12  15.0    45.0
Egypt                       1   NaN     NaN
England                    74  25.0    95.0
France                  22093   5.0  3300.0
Georgia                    86   9.0    40.0
Germany                  2165   5.0   775.0
Greece                    466   8.0    79.0
Hungary                   146  10.0   764.0
India                       9  10.0    20.0
Israel                    505   8.0   150.0
Italy                   19540   5.0   900.0
Lebanon                    35  13.0    75.0
Luxembourg                  6  16.0    30.0
Macedonia                  12  15.0    20.0
Mexico                     70   8.0   108.0
Moldova                    59   8.0    42.0
Morocco                    28  14.0    40.0
New Zealand              1419   7.0   130.0
Peru                       16  10.0    68.0
Portugal                 5691   5.0  1000.0
Romania                   120   4.0   320.0
Serbia                     12  15.0    42.0
Slovakia                    1  16.0    16.0
Slovenia                   87   7.0    90.0
South Africa             1401   5.0   330.0
Spain                    6645   4.0   770.0
Switzerland                 7  21.0   160.0
Turkey                     90  14.0   120.0
US                      54504   4.0  2013.0
Ukraine                    14   6.0    13.0
Uruguay                   109  10.0   130.0

In [20]:
sortby = sorted_by_country.reset_index()
sortby

                   country    len   min     max
0                Argentina   3800   4.0   230.0
1                  Armenia      2  14.0    15.0
2                Australia   2329   5.0   850.0
3                  Austria   3345   7.0  1100.0
4   Bosnia and Herzegovina      2  12.0    13.0
5                   Brazil     52  10.0    60.0
6                 Bulgaria    141   8.0   100.0
7                   Canada    257  12.0   120.0
8                    Chile   4472   5.0   400.0
9                    China      1  18.0    18.0
10                 Croatia     73  12.0    65.0
11                  Cyprus     11  11.0    21.0
12          Czech Republic     12  15.0    45.0
13                   Egypt      1   NaN     NaN
14                 England     74  25.0    95.0
15                  France  22093   5.0  3300.0
16                 Georgia     86   9.0    40.0
17                 Germany   2165   5.0   775.0
18                  Greece    466   8.0    79.0
19                 Hungary    146  10.0   764.0
20                   India      9  10.0    20.0
21                  Israel    505   8.0   150.0
22                   Italy  19540   5.0   900.0
23                 Lebanon     35  13.0    75.0
24              Luxembourg      6  16.0    30.0
25               Macedonia     12  15.0    20.0
26                  Mexico     70   8.0   108.0
27                 Moldova     59   8.0    42.0
28                 Morocco     28  14.0    40.0
29             New Zealand   1419   7.0   130.0
30                    Peru     16  10.0    68.0
31                Portugal   5691   5.0  1000.0
32                 Romania    120   4.0   320.0
33                  Serbia     12  15.0    42.0
34                Slovakia      1  16.0    16.0
35                Slovenia     87   7.0    90.0
36            South Africa   1401   5.0   330.0
37                   Spain   6645   4.0   770.0
38             Switzerland      7  21.0   160.0
39                  Turkey     90  14.0   120.0
40                      US  54504   4.0  2013.0
41                 Ukraine     14   6.0    13.0
42                 Uruguay    109  10.0   130.0

In [21]:
sortby.sort_values(by="len")

                   country    len   min     max
9                    China      1  18.0    18.0
34                Slovakia      1  16.0    16.0
13                   Egypt      1   NaN     NaN
1                  Armenia      2  14.0    15.0
4   Bosnia and Herzegovina      2  12.0    13.0
24              Luxembourg      6  16.0    30.0
38             Switzerland      7  21.0   160.0
20                   India      9  10.0    20.0
11                  Cyprus     11  11.0    21.0
12          Czech Republic     12  15.0    45.0
33                  Serbia     12  15.0    42.0
25               Macedonia     12  15.0    20.0
41                 Ukraine     14   6.0    13.0
30                    Peru     16  10.0    68.0
28                 Morocco     28  14.0    40.0
23                 Lebanon     35  13.0    75.0
5                   Brazil     52  10.0    60.0
27                 Moldova     59   8.0    42.0
26                  Mexico     70   8.0   108.0
10                 Croatia     73  12.0    65.0
14                 England     74  25.0    95.0
16                 Georgia     86   9.0    40.0
35                Slovenia     87   7.0    90.0
39                  Turkey     90  14.0   120.0
42                 Uruguay    109  10.0   130.0
32                 Romania    120   4.0   320.0
6                 Bulgaria    141   8.0   100.0
19                 Hungary    146  10.0   764.0
7                   Canada    257  12.0   120.0
18                  Greece    466   8.0    79.0
21                  Israel    505   8.0   150.0
36            South Africa   1401   5.0   330.0
29             New Zealand   1419   7.0   130.0
17                 Germany   2165   5.0   775.0
2                Australia   2329   5.0   850.0
3                  Austria   3345   7.0  1100.0
0                Argentina   3800   4.0   230.0
8                    Chile   4472   5.0   400.0
31                Portugal   5691   5.0  1000.0
37                   Spain   6645   4.0   770.0
22                   Italy  19540   5.0   900.0
15                  France  22093   5.0  3300.0
40                      US  54504   4.0  2013.0

In [22]:
sortby.sort_values(by= "max")

                   country    len   min     max
41                 Ukraine     14   6.0    13.0
4   Bosnia and Herzegovina      2  12.0    13.0
1                  Armenia      2  14.0    15.0
34                Slovakia      1  16.0    16.0
9                    China      1  18.0    18.0
20                   India      9  10.0    20.0
25               Macedonia     12  15.0    20.0
11                  Cyprus     11  11.0    21.0
24              Luxembourg      6  16.0    30.0
28                 Morocco     28  14.0    40.0
16                 Georgia     86   9.0    40.0
33                  Serbia     12  15.0    42.0
27                 Moldova     59   8.0    42.0
12          Czech Republic     12  15.0    45.0
5                   Brazil     52  10.0    60.0
10                 Croatia     73  12.0    65.0
30                    Peru     16  10.0    68.0
23                 Lebanon     35  13.0    75.0
18                  Greece    466   8.0    79.0
35                Slovenia     87   7.0    90.0
14                 England     74  25.0    95.0
6                 Bulgaria    141   8.0   100.0
26                  Mexico     70   8.0   108.0
7                   Canada    257  12.0   120.0
39                  Turkey     90  14.0   120.0
29             New Zealand   1419   7.0   130.0
42                 Uruguay    109  10.0   130.0
21                  Israel    505   8.0   150.0
38             Switzerland      7  21.0   160.0
0                Argentina   3800   4.0   230.0
32                 Romania    120   4.0   320.0
36            South Africa   1401   5.0   330.0
8                    Chile   4472   5.0   400.0
19                 Hungary    146  10.0   764.0
37                   Spain   6645   4.0   770.0
17                 Germany   2165   5.0   775.0
2                Australia   2329   5.0   850.0
22                   Italy  19540   5.0   900.0
31                Portugal   5691   5.0  1000.0
3                  Austria   3345   7.0  1100.0
40                      US  54504   4.0  2013.0
15                  France  22093   5.0  3300.0
13                   Egypt      1   NaN     NaN

# Exercises

## 1.
Who are the most common wine reviewers in the dataset? Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, and whose values count how many reviews each person wrote.

In [35]:
# Your code here
reviews_written = reviews.groupby("taster_twitter_handle").taster_twitter_handle.count()

# Check your answer
q1.check()

Correct:


```python
reviews_written = reviews.groupby('taster_twitter_handle').size()
```
or
```python
reviews_written = reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()
```

In [32]:
q1.hint()
q1.solution()

Hint: Use the `groupby` operation and `size()` (or `count()`).

Solution:
```python
reviews_written = reviews.groupby('taster_twitter_handle').size()
```
or
```python
reviews_written = reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()
```

## 2.
What is the best wine I can buy for a given amount of money? Create a `Series` whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that `4.0` dollars is at the top and `3300.0` dollars is at the bottom).

In [54]:
best_rating_per_price = reviews.groupby("price")["points"].max().sort_index()
# Check your answer
q2.check()

Correct

In [55]:
reviews.groupby("price")["points"].max().sort_index

<bound method Series.sort_index of price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64>

In [50]:
q2.hint()
q2.solution()

Hint: Use `max()` and `sort_index()`.  The relevant columns in the DataFrame are `price` and `points`.

Solution:
```python
best_rating_per_price = reviews.groupby('price')['points'].max().sort_index()
```

## 3.
What are the minimum and maximum prices for each `variety` of wine? Create a `DataFrame` whose index is the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

In [64]:
price_extremes = reviews.groupby(["variety"]).price.agg([min,max])

# Check your answer
q3.check()

Correct

In [63]:
q3.hint()
q3.solution()

Hint: Use `agg()`.

Solution:
```python
price_extremes = reviews.groupby('variety').price.agg([min, max])
```

## 4.
What are the most expensive wine varieties? Create a variable `sorted_varieties` containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [65]:
sorted_varieties = price_extremes.sort_values(by = ["min","max"],ascending = False)

# Check your answer
q4.check()

Correct

In [ ]:
#q4.hint()
#q4.solution()

## 5.
Create a `Series` whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the `taster_name` and `points` columns.

In [70]:
reviewer_mean_ratings = reviews.groupby("taster_name").points.mean()

# Check your answer
q5.check()

Correct

In [67]:
q5.hint()
q5.solution()

Hint: Use `mean()`.

Solution:
```python
reviewer_mean_ratings = reviews.groupby('taster_name').points.mean()
```

Are there significant differences in the average scores assigned by the various reviewers? Run the cell below to use the `describe()` method to see a summary of the range of values.

In [71]:
reviewer_mean_ratings.describe()

count    19.000000
mean     88.233026
std       1.243610
min      85.855422
25%      87.323501
50%      88.536235
75%      88.975256
max      90.562551
Name: points, dtype: float64

## 6.
What combination of countries and varieties are most common? Create a `Series` whose index is a `MultiIndex`of `{country, variety}` pairs. For example, a pinot noir produced in the US should map to `{"US", "Pinot Noir"}`. Sort the values in the `Series` in descending order based on wine count.

In [74]:
country_variety_counts = reviews.groupby(["country","variety"]).size().sort_values(ascending = False)

# Check your answer
q6.check()

Correct

In [73]:
q6.hint()
q6.solution()

Hint: Use `groupby()`, and provide a list of columns to group by.  You may also find `size()` and `sort_values()` to be useful!

Solution:
```python
country_variety_counts = reviews.groupby(['country', 'variety']).size().sort_values(ascending=False)
```

# Keep going

Move on to the [**data types and missing data**](https://www.kaggle.com/residentmario/data-types-and-missing-values).

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*